---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provenance-redis
  namespace: humun-core-crypto
  labels:
    app: provenance-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provenance-redis
  template:
    metadata:
      labels:
        app: provenance-redis
    spec:
      containers:
      - name: redis
        image: redis:6
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 4000m
            memory: 16Gi
        ports:
          - containerPort: 6379
            name: tcp-redis
        volumeMounts:
        - name: redis
          mountPath: /data
      volumes:
      - name: redis
        persistentVolumeClaim:
          claimName: provenance-redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: provenance-redis
  namespace: humun-core-crypto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: provenance-redis
  namespace: humun-core-crypto
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: provenance-redis
  ports:
    - protocol: TCP
      name: tcp-redis
      port: 6379
      targetPort: 6379
